apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: cilium
spec:
  targetNamespace: kube-system
  createNamespace: false
  version: v1.16.1
  chart: cilium
  repo: https://helm.cilium.io/
  valuesContent: |-
    k8sServiceHost: 192.168.122.11
    k8sServicePort: 6443
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    k8sClientRateLimit:
      qps: 50
      burst: 200
    operator:
      replicas: 1  # Uncomment this if you only have one node
      rollOutPods: true
    rollOutCiliumPods: true
    ingressController:
      enabled: true
      default: true
      loadbalancerMode: shared
      service:
        annotations:
          io.cilium/lb-ipam-ips: 192.168.100.1
